image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
  - test
  - release
  - deploy

cypress:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    - env | ( grep YAWIK || echo "ROUTER_BASE=/${CI_PAGES_URL#*://*/}/" )  > .env
    - yarn 
    - yarn dev &
    - sleep 20
    - npx cypress run form_submit.spec.js

publish:
  stage: release
  script:
    - env | ( grep YAWIK && yarn && yarn semantic-release || echo "skip semantic-release" ) > /dev/null
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - env | ( grep YAWIK || echo "ROUTER_BASE=/${CI_PAGES_URL#*://*/}/" )  > .env
    - yarn
    - yarn build
    - mkdir .public
    - cp -r dist/spa/* .public
    - cp dist/spa/index.html .public/404.html
    - rm -Rf public
    - mv .public public
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      - public
  only:
    - master
