image: node:12.14.1

cache:
  paths:
    - node_modules/
pages:
  stage: deploy
  script:
  - env
  - env | grep YAWIK > .env
  - npm install
  - npx quasar build
  - mkdir .public
  - cp -r dist/spa/* .public
  - cp dist/spa/index.html .public/404.html
  - rm -Rf public
  - mv .public public
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - public
  only:
  - master
